export const LIKE_DISLIKE_ARTICLE_REQUEST = 'LIKE_DISLIKE_ARTICLE_REQUEST';
export const LIKE_DISLIKE_ARTICLE_SUCCESS = 'LIKE_DISLIKE_ARTICLE_SUCCESS';
export const LIKE_DISLIKE_ARTICLE_FAILURE = 'LIKE_DISLIKE_ARTICLE_FAILURE';
