export const SUCCESS_PROFILE = 'SUCCESS_PROFILE';
export const FAIL_PROFILE = 'FAIL_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE';
