export const GOOGLE = 'GOOGLE_ACCESS_CODE_SUCCESS';
export const FACEBOOK = 'FACEBOOK_ACCESS_CODE_SUCCESS';
export const TWITTER = 'TWITTER_ACCESS_CODE_SUCCESS';
export const SOCIAL_AUTH_REQUEST = 'SOCIAL_AUTH_REQUEST';
export const FETCHING = 'FETCHING';
export const FETCH_FAILED = 'FETCH_FAILED';
