/* eslint-disable import/prefer-default-export */
export const GET_RESETPASSWORD_REQUEST = 'RESETPASSWORD_REQUEST';
export const UPDATE_PASSWORD_REQUEST = 'UPDATEPASSWORD_REQUEST';
export const GET_RESETPASSWORD_SUCCESS = 'RESETPASSWORD_SUCCESS';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const GET_RESETPASSWORD_FAILURE = 'RESETPASSWORD_FAILURE';
export const UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE';
